### ISSUE TITLE
The Content-Range header is missing in the HTTP Response

### ISSUE THREAD

**Issue by devalexandre** [nazirov91/ra-strapi-rest#13]
after login using it

```javascript
import React from 'react';
import authProvider from './authProvider';
//import dataProvider from './dataProvider';
import { fetchUtils, Admin, Resource ,ListGuesser} from 'react-admin';
import simpleRestProvider from './helpers/rest.strapi';
import { apiUrl  } from './config';

const httpClient = (url, options = {}) => {
  if (!options.headers) {
      options.headers = new Headers({ Accept: 'application/json' });
  }
  const token = localStorage.getItem('token');
  options.headers.set('Authorization', `Bearer ${token}`);
  return fetchUtils.fetchJson(url, options);
}

const dataProvider = simpleRestProvider(apiUrl, httpClient);

const App = () => (
  <Admin authProvider={authProvider} dataProvider={dataProvider}>
      <Resource name="products" list={ListGuesser} />
  </Admin>
);

export default App;
```
display it
```
The Content-Range header is missing in the HTTP Response. The simple REST data provider expects responses for lists of resources to contain this header with the total number of results to build the pagination. If you are using CORS, did you declare Content-Range in the Access-Control-Expose-Headers header?

```

**Comment by nazirov91** [comment]
@devalexandre 
- Make sure CORS is enabled in Strapi project
- Add Content-Range to expose headers object in <your_project>/config/environments/development/security.js

```js
"cors": {
    "enabled": true,
    "origin": "*",
    "expose": [
      "WWW-Authenticate",
      "Server-Authorization",
      "Content-Range" // <<--- HERE
    ],
    ...
  },
  ...
}
```

**Comment by nazirov91** [comment]
or if you are using the Strapi Beta version, you need to override the find method for Products controller

```js 
// api/post/controllers/Products.js

'use strict';
const { sanitizeEntity } = require('strapi-utils');

module.exports = {
  async find(ctx) {
    let entities;
    ctx.set('Content-Range', await strapi.services.product.count()); // <--- Don't forget this guy
    if (ctx.query._q) {
      entities = await strapi.services.product.search(ctx.query);
    } else {
      entities = await strapi.services.product.find(ctx.query);
    }

    return entities.map(entity =>
      sanitizeEntity(entity, { model: strapi.models.product })
    );
  },
};
```

**Comment by devalexandre** [comment]
when I alter controll display it

```
 Server wasn't able to start properly.
[2020-03-17T01:57:46.570Z] error TypeError: Cannot read property 'bind' of undefined
    at routerChecker (/Users/alexandre/projetos/cardapio-online/backend/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:35:43)
    at /Users/alexandre/projetos/cardapio-online/backend/node_modules/strapi/lib/middlewares/router/utils/composeEndpoint.js:15:52
    at /Users/alexandre/projetos/cardapio-online/backend/node_modules/strapi/lib/middlewares/router/index.js:25:9
    at arrayEach (/Users/alexandre/projetos/cardapio-online/backend/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/Users/alexandre/projetos/cardapio-online/backend/node_modules/lodash/lodash.js:9342:14)
    at Object.initialize (/Users/alexandre/projetos/cardapio-online/backend/node_modules/strapi/lib/middlewares/router/index.js:24:9)
    at /Users/alexandre/projetos/cardapio-online/backend/node_modules/strapi/lib/middlewares/index.js:43:28
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by nazirov91** [comment]
> when I alter controll display it
> 
> ```
>  Server wasn't able to start properly.
> [2020-03-17T01:57:46.570Z] error TypeError: Cannot read property 'bind' of undefined
>     at routerChecker (/Users/alexandre/projetos/cardapio-online/backend/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:35:43)
>     at /Users/alexandre/projetos/cardapio-online/backend/node_modules/strapi/lib/middlewares/router/utils/composeEndpoint.js:15:52
>     at /Users/alexandre/projetos/cardapio-online/backend/node_modules/strapi/lib/middlewares/router/index.js:25:9
>     at arrayEach (/Users/alexandre/projetos/cardapio-online/backend/node_modules/lodash/lodash.js:516:11)
>     at Function.forEach (/Users/alexandre/projetos/cardapio-online/backend/node_modules/lodash/lodash.js:9342:14)
>     at Object.initialize (/Users/alexandre/projetos/cardapio-online/backend/node_modules/strapi/lib/middlewares/router/index.js:24:9)
>     at /Users/alexandre/projetos/cardapio-online/backend/node_modules/strapi/lib/middlewares/index.js:43:28
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

Is it happening only when you modify the controller?

Have you tried this option: https://github.com/strapi/strapi/issues/4042
